name: flutter_rtmp_publisher
description: Flutter plugin to broadcast live via RTMP. Forked from https://github.com/PonnamKarthik/FlutterRtmpPlublisher by Karthik Ponnam <ponnamkarthik3@gmail.com>
version: 0.0.1
author: Alex Heritier <alex.heritier@gmail.com>
homepage: https://github.com/alex-heritier/flutter-rtmp-publisher

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.github.alex_heritier.flutter_rtmp_publisher
    pluginClass: FlutterRtmpPublisherPlugin

  assets:
   - images/